#pragma once

#include "components/themes/lyra/LyraCarouselTheme.h"
#include "components/themes/lyra/LyraGridLayout.h"

class GfxRenderer;

// Lyra Grid: Lyra Carousel's bottom icon menu with a 3x2 grid of recent and pinned books.
namespace LyraGridMetrics {
constexpr ThemeMetrics makeValues() {
  ThemeMetrics v = LyraCarouselMetrics::values;
  // Exact thumbnail height generated by Home; a 2:3 cover is 136x204 and fits a tile without scaling.
  v.homeCoverHeight = 204;
  v.homeCoverTileHeight = 650;
  v.homeRecentBooksCount = 6;
  v.homeMenuTopOffset = 0;
  return v;
}

constexpr ThemeMetrics values = makeValues();
}  // namespace LyraGridMetrics

class LyraGridTheme : public LyraCarouselTheme {
 public:
  static constexpr int kTileCount = LyraGridLayout::kTileCount;

  // Home publishes each visible book's progress before rendering; negative hides the bar.
  static void setTileProgress(int index, float progressPercent);
  static void clearTileProgress();

  void drawRecentBookCover(GfxRenderer& renderer, Rect rect, const std::vector<RecentBook>& recentBooks,
                           int selectorIndex, bool& coverRendered, bool& coverBufferStored, bool& bufferRestored,
                           const std::function<bool()>& storeCoverBuffer, const BookReadingStats* stats = nullptr,
                           float progressPercent = -1.0f, const GlobalReadingStats* globalStats = nullptr,
                           const char* currentChapterTitle = nullptr) const override;
};
